### ISSUE TITLE
TypeError: __init__() got multiple values for argument 'on_delete'

### ISSUE THREAD

**Issue by leofelipe222** [Jordan-Kowal/django_database_translation#1]
I am trying to use this library to translate an existing app and I'm getting the error above.

ERROR:
  class Programa(models.Model, TranslatedModel):
  File "/Users/josesouza/Desktop/soskardec_project/programacao/models.py", line 12, in Programa
    title = TranslatedField(models.CharField(max_length=200))
  File "/Users/josesouza/Desktop/soskardec_project/venv/lib/python3.7/site-packages/django_database_translation/fields.py", line 51, in TranslatedField
    return models.ForeignKey("django_database_translation.Item", *args, **kwargs)
TypeError: __init__() got multiple values for argument 'on_delete'

Here is my models.py file:

```python
from django.db import models
from voluntarios.models import Voluntario
from PIL import Image
from django_database_translation.fields import TranslatedField
from django_database_translation.models import TranslatedModel


class Programa(models.Model, TranslatedModel):
    # If the volunteer is deleted the event still remains in the DB
    volunteer = models.ForeignKey(Voluntario, on_delete=models.DO_NOTHING)
    title = TranslatedField(models.CharField(max_length=200))
    description = TranslatedField(models.TextField(blank=True))
    program_type = TranslatedField(models.CharField(max_length=200))
    program_date = TranslatedField(models.DateTimeField(blank=True))
    is_published = models.BooleanField(default=True)
    photo_main = models.ImageField(upload_to='photos/%Y%m%d/')
    
    def __str__(self):
        return self.title # displays title as the main field in the admin area```

**Comment by Jordan-Kowal** [comment]
Hey there,
I did not expect anyone to be using my module but I'm glad you're giving it a try

**1.** I think I know why it's not working. `TranslatedField` is a model field. It is technically a ForeignKey field linked to our `Item` model. In your example, you're doing `TranslatedField(models.CharField(max_length=200))` which is like writing `model.field(model.field))` hence why it's not working.

**2.** Also, you should only use `TranslatedField` for fields that would ultimately end up with raw text (charfield/textarea), not dates. 

**3.** Finally, because `TranslatedFIeld` is a foreignkey, you can't specify attributes specific to charfields like max_length (as it doesn't apply and other stuff like that). But make sure you always declare a `verbose_name` and a unique `related_name`

**4.** Also please note that `TranslatedModel` already inherits from `models.Model`, so you don't have to use both when creating a new model

Your model should basically look like this:

```python
class Programa(TranslatedModel):
    # If the volunteer is deleted the event still remains in the DB
    volunteer = models.ForeignKey(Voluntario, on_delete=models.DO_NOTHING)
    title = TranslatedField(
        related_name="programa_title",
        verbose_name="Title"
    )
    description = TranslatedField(
        related_name="programa_description",
        verbose_name="Description"
    )
    # You could also create a Type model with translations, and simply use a FK here, like you did for 'volunteer'
    program_type = TranslatedField(
        related_name="programa_type",
        verbose_name="Type"
    )
    program_date = models.DateTimeField(blank=True)
    is_published = models.BooleanField(default=True)
    photo_main = models.ImageField(upload_to='photos/%Y%m%d/')
    
    def __str__(self):
        return self.title # displays title as the main field in the admin area```
```

You can check this part of the README to have a complete example:
 https://github.com/Jordan-Kowal/django_database_translation#2-updating-your-models

Let me know if it helps

**Comment by leofelipe222** [comment]
I updated the code with your version of it, but when I try to run the migrations I get this and I did not have this before, not sure what to do here:
````
(venv) joses-MacBook-Pro:soskardec_project$ python manage.py makemigrations django_database_translation
You are trying to add a non-nullable field 'meta_info' to programa without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py
Select an option: ```

**Comment by Jordan-Kowal** [comment]
This is standard Django behavior.
- You have a model called **Programa** that already has existing rows.
- You changed that model
- More specifically, you added a parent class which triggered the creation of a new field called **meta_info** in your model
- This field cannot be null
- Django is telling you _You want to add a field that cannot be null onto rows that already exist. Because it cannot be null, you must give me a default value_

So pick option 1 and set a default value that will be set into the **meta_info** of all your existing rows

**Comment by Jordan-Kowal** [comment]
Also, please note that your previous values in `title`, `description` and `program_type ` **will be erased**. You probably had a text/charfield, and we replaced it with a foreign key field. If you wish to use their existing values in your translations, save them somewhere else and input them in the new translation fields once you're done
